<?php

declare(strict_types=1);

/**
 * Phase 2: Update all namespace references across the codebase
 * Run after scripts/refactor-domains.php has copied files to app/Domain/
 */

$root = dirname(__DIR__);
chdir($root);

$oldToNew = [
    // Auth
    'App\Models\Role' => 'App\Domain\Auth\Models\Role',
    'App\Models\User' => 'App\Domain\Auth\Models\User',
    'App\Http\Controllers\Api\AuthController' => 'App\Domain\Auth\Controllers\AuthController',
    'App\Http\Controllers\Api\RoleController' => 'App\Domain\Auth\Controllers\RoleController',
    'App\Http\Controllers\Api\UserController' => 'App\Domain\Auth\Controllers\UserController',
    'App\Services\RoleService' => 'App\Domain\Auth\Services\RoleService',
    'App\Services\UserService' => 'App\Domain\Auth\Services\UserService',
    'App\Services\Contracts\RoleServiceInterface' => 'App\Domain\Auth\Services\Contracts\RoleServiceInterface',
    'App\Services\Contracts\UserServiceInterface' => 'App\Domain\Auth\Services\Contracts\UserServiceInterface',
    'App\Repositories\Eloquent\RoleRepository' => 'App\Domain\Auth\Repositories\Eloquent\RoleRepository',
    'App\Repositories\Eloquent\UserRepository' => 'App\Domain\Auth\Repositories\Eloquent\UserRepository',
    'App\Repositories\Contracts\RoleRepositoryInterface' => 'App\Domain\Auth\Repositories\Contracts\RoleRepositoryInterface',
    'App\Repositories\Contracts\UserRepositoryInterface' => 'App\Domain\Auth\Repositories\Contracts\UserRepositoryInterface',
    'App\Http\Requests\RoleRequest' => 'App\Domain\Auth\Requests\RoleRequest',
    'App\Http\Requests\UserRequest' => 'App\Domain\Auth\Requests\UserRequest',
    'App\Http\Resources\RoleResource' => 'App\Domain\Auth\Resources\RoleResource',
    'App\Http\Resources\RoleCollection' => 'App\Domain\Auth\Resources\RoleCollection',
    'App\Http\Resources\UserResource' => 'App\Domain\Auth\Resources\UserResource',
    'App\Http\Resources\UserCollection' => 'App\Domain\Auth\Resources\UserCollection',
    'App\Providers\RoleServiceProvider' => 'App\Domain\Auth\Providers\RoleServiceProvider',
    'App\Providers\UserServiceProvider' => 'App\Domain\Auth\Providers\UserServiceProvider',

    // Academic
    'App\Models\AcademicYear' => 'App\Domain\Academic\Models\AcademicYear',
    'App\Models\Term' => 'App\Domain\Academic\Models\Term',
    'App\Models\ClassLevel' => 'App\Domain\Academic\Models\ClassLevel',
    'App\Models\Stream' => 'App\Domain\Academic\Models\Stream',
    'App\Http\Controllers\Api\AcademicYearController' => 'App\Domain\Academic\Controllers\AcademicYearController',
    'App\Http\Controllers\Api\TermController' => 'App\Domain\Academic\Controllers\TermController',
    'App\Http\Controllers\Api\ClassLevelController' => 'App\Domain\Academic\Controllers\ClassLevelController',
    'App\Http\Controllers\Api\StreamController' => 'App\Domain\Academic\Controllers\StreamController',
    'App\Services\AcademicYearService' => 'App\Domain\Academic\Services\AcademicYearService',
    'App\Services\TermService' => 'App\Domain\Academic\Services\TermService',
    'App\Services\ClassLevelService' => 'App\Domain\Academic\Services\ClassLevelService',
    'App\Services\StreamService' => 'App\Domain\Academic\Services\StreamService',
    'App\Services\Contracts\AcademicYearServiceInterface' => 'App\Domain\Academic\Services\Contracts\AcademicYearServiceInterface',
    'App\Services\Contracts\TermServiceInterface' => 'App\Domain\Academic\Services\Contracts\TermServiceInterface',
    'App\Services\Contracts\ClassLevelServiceInterface' => 'App\Domain\Academic\Services\Contracts\ClassLevelServiceInterface',
    'App\Services\Contracts\StreamServiceInterface' => 'App\Domain\Academic\Services\Contracts\StreamServiceInterface',
    'App\Repositories\Eloquent\AcademicYearRepository' => 'App\Domain\Academic\Repositories\Eloquent\AcademicYearRepository',
    'App\Repositories\Eloquent\TermRepository' => 'App\Domain\Academic\Repositories\Eloquent\TermRepository',
    'App\Repositories\Eloquent\ClassLevelRepository' => 'App\Domain\Academic\Repositories\Eloquent\ClassLevelRepository',
    'App\Repositories\Eloquent\StreamRepository' => 'App\Domain\Academic\Repositories\Eloquent\StreamRepository',
    'App\Repositories\Contracts\AcademicYearRepositoryInterface' => 'App\Domain\Academic\Repositories\Contracts\AcademicYearRepositoryInterface',
    'App\Repositories\Contracts\TermRepositoryInterface' => 'App\Domain\Academic\Repositories\Contracts\TermRepositoryInterface',
    'App\Repositories\Contracts\ClassLevelRepositoryInterface' => 'App\Domain\Academic\Repositories\Contracts\ClassLevelRepositoryInterface',
    'App\Repositories\Contracts\StreamRepositoryInterface' => 'App\Domain\Academic\Repositories\Contracts\StreamRepositoryInterface',
    'App\Http\Requests\AcademicYearRequest' => 'App\Domain\Academic\Requests\AcademicYearRequest',
    'App\Http\Requests\TermRequest' => 'App\Domain\Academic\Requests\TermRequest',
    'App\Http\Requests\ClassLevelRequest' => 'App\Domain\Academic\Requests\ClassLevelRequest',
    'App\Http\Requests\StreamRequest' => 'App\Domain\Academic\Requests\StreamRequest',
    'App\Http\Resources\AcademicYearResource' => 'App\Domain\Academic\Resources\AcademicYearResource',
    'App\Http\Resources\AcademicYearCollection' => 'App\Domain\Academic\Resources\AcademicYearCollection',
    'App\Http\Resources\TermResource' => 'App\Domain\Academic\Resources\TermResource',
    'App\Http\Resources\TermCollection' => 'App\Domain\Academic\Resources\TermCollection',
    'App\Http\Resources\ClassLevelResource' => 'App\Domain\Academic\Resources\ClassLevelResource',
    'App\Http\Resources\ClassLevelCollection' => 'App\Domain\Academic\Resources\ClassLevelCollection',
    'App\Http\Resources\StreamResource' => 'App\Domain\Academic\Resources\StreamResource',
    'App\Http\Resources\StreamCollection' => 'App\Domain\Academic\Resources\StreamCollection',
    'App\Providers\AcademicYearServiceProvider' => 'App\Domain\Academic\Providers\AcademicYearServiceProvider',
    'App\Providers\TermServiceProvider' => 'App\Domain\Academic\Providers\TermServiceProvider',
    'App\Providers\ClassLevelServiceProvider' => 'App\Domain\Academic\Providers\ClassLevelServiceProvider',
    'App\Providers\StreamServiceProvider' => 'App\Domain\Academic\Providers\StreamServiceProvider',

    // Staff
    'App\Models\Staff' => 'App\Domain\Staff\Models\Staff',
    'App\Http\Controllers\Api\StaffController' => 'App\Domain\Staff\Controllers\StaffController',
    'App\Services\StaffService' => 'App\Domain\Staff\Services\StaffService',
    'App\Services\Contracts\StaffServiceInterface' => 'App\Domain\Staff\Services\Contracts\StaffServiceInterface',
    'App\Repositories\Eloquent\StaffRepository' => 'App\Domain\Staff\Repositories\Eloquent\StaffRepository',
    'App\Repositories\Contracts\StaffRepositoryInterface' => 'App\Domain\Staff\Repositories\Contracts\StaffRepositoryInterface',
    'App\Http\Requests\StaffRequest' => 'App\Domain\Staff\Requests\StaffRequest',
    'App\Http\Resources\StaffResource' => 'App\Domain\Staff\Resources\StaffResource',
    'App\Http\Resources\StaffCollection' => 'App\Domain\Staff\Resources\StaffCollection',
    'App\Providers\StaffServiceProvider' => 'App\Domain\Staff\Providers\StaffServiceProvider',

    // Students
    'App\Models\Student' => 'App\Domain\Students\Models\Student',
    'App\Models\Guardian' => 'App\Domain\Students\Models\Guardian',
    'App\Models\StudentGuardian' => 'App\Domain\Students\Models\StudentGuardian',
    'App\Models\Enrollment' => 'App\Domain\Students\Models\Enrollment',
    'App\Http\Controllers\Api\StudentController' => 'App\Domain\Students\Controllers\StudentController',
    'App\Http\Controllers\Api\GuardianController' => 'App\Domain\Students\Controllers\GuardianController',
    'App\Http\Controllers\Api\EnrollmentController' => 'App\Domain\Students\Controllers\EnrollmentController',
    'App\Services\StudentService' => 'App\Domain\Students\Services\StudentService',
    'App\Services\GuardianService' => 'App\Domain\Students\Services\GuardianService',
    'App\Services\StudentGuardianService' => 'App\Domain\Students\Services\StudentGuardianService',
    'App\Services\EnrollmentService' => 'App\Domain\Students\Services\EnrollmentService',
    'App\Services\Contracts\StudentServiceInterface' => 'App\Domain\Students\Services\Contracts\StudentServiceInterface',
    'App\Services\Contracts\GuardianServiceInterface' => 'App\Domain\Students\Services\Contracts\GuardianServiceInterface',
    'App\Services\Contracts\StudentGuardianServiceInterface' => 'App\Domain\Students\Services\Contracts\StudentGuardianServiceInterface',
    'App\Services\Contracts\EnrollmentServiceInterface' => 'App\Domain\Students\Services\Contracts\EnrollmentServiceInterface',
    'App\Repositories\Eloquent\StudentRepository' => 'App\Domain\Students\Repositories\Eloquent\StudentRepository',
    'App\Repositories\Eloquent\GuardianRepository' => 'App\Domain\Students\Repositories\Eloquent\GuardianRepository',
    'App\Repositories\Eloquent\StudentGuardianRepository' => 'App\Domain\Students\Repositories\Eloquent\StudentGuardianRepository',
    'App\Repositories\Eloquent\EnrollmentRepository' => 'App\Domain\Students\Repositories\Eloquent\EnrollmentRepository',
    'App\Repositories\Contracts\StudentRepositoryInterface' => 'App\Domain\Students\Repositories\Contracts\StudentRepositoryInterface',
    'App\Repositories\Contracts\GuardianRepositoryInterface' => 'App\Domain\Students\Repositories\Contracts\GuardianRepositoryInterface',
    'App\Repositories\Contracts\StudentGuardianRepositoryInterface' => 'App\Domain\Students\Repositories\Contracts\StudentGuardianRepositoryInterface',
    'App\Repositories\Contracts\EnrollmentRepositoryInterface' => 'App\Domain\Students\Repositories\Contracts\EnrollmentRepositoryInterface',
    'App\Http\Requests\StudentRequest' => 'App\Domain\Students\Requests\StudentRequest',
    'App\Http\Requests\GuardianRequest' => 'App\Domain\Students\Requests\GuardianRequest',
    'App\Http\Requests\EnrollmentRequest' => 'App\Domain\Students\Requests\EnrollmentRequest',
    'App\Http\Resources\StudentResource' => 'App\Domain\Students\Resources\StudentResource',
    'App\Http\Resources\StudentCollection' => 'App\Domain\Students\Resources\StudentCollection',
    'App\Http\Resources\GuardianResource' => 'App\Domain\Students\Resources\GuardianResource',
    'App\Http\Resources\GuardianCollection' => 'App\Domain\Students\Resources\GuardianCollection',
    'App\Http\Resources\EnrollmentResource' => 'App\Domain\Students\Resources\EnrollmentResource',
    'App\Http\Resources\EnrollmentCollection' => 'App\Domain\Students\Resources\EnrollmentCollection',
    'App\Providers\StudentServiceProvider' => 'App\Domain\Students\Providers\StudentServiceProvider',
    'App\Providers\GuardianServiceProvider' => 'App\Domain\Students\Providers\GuardianServiceProvider',
    'App\Providers\StudentGuardianServiceProvider' => 'App\Domain\Students\Providers\StudentGuardianServiceProvider',
    'App\Providers\EnrollmentServiceProvider' => 'App\Domain\Students\Providers\EnrollmentServiceProvider',

    // Curriculum
    'App\Models\Subject' => 'App\Domain\Curriculum\Models\Subject',
    'App\Models\ClassSubject' => 'App\Domain\Curriculum\Models\ClassSubject',
    'App\Models\SubjectTeacher' => 'App\Domain\Curriculum\Models\SubjectTeacher',
    'App\Models\CurriculumTheme' => 'App\Domain\Curriculum\Models\CurriculumTheme',
    'App\Models\LearningOutcome' => 'App\Domain\Curriculum\Models\LearningOutcome',
    'App\Models\GenericSkill' => 'App\Domain\Curriculum\Models\GenericSkill',
    'App\Http\Controllers\Api\SubjectController' => 'App\Domain\Curriculum\Controllers\SubjectController',
    'App\Http\Controllers\Api\ClassSubjectController' => 'App\Domain\Curriculum\Controllers\ClassSubjectController',
    'App\Http\Controllers\Api\SubjectTeacherController' => 'App\Domain\Curriculum\Controllers\SubjectTeacherController',
    'App\Http\Controllers\Api\CurriculumThemeController' => 'App\Domain\Curriculum\Controllers\CurriculumThemeController',
    'App\Http\Controllers\Api\LearningOutcomeController' => 'App\Domain\Curriculum\Controllers\LearningOutcomeController',
    'App\Http\Controllers\Api\GenericSkillController' => 'App\Domain\Curriculum\Controllers\GenericSkillController',
    'App\Services\SubjectService' => 'App\Domain\Curriculum\Services\SubjectService',
    'App\Services\ClassSubjectService' => 'App\Domain\Curriculum\Services\ClassSubjectService',
    'App\Services\SubjectTeacherService' => 'App\Domain\Curriculum\Services\SubjectTeacherService',
    'App\Services\CurriculumThemeService' => 'App\Domain\Curriculum\Services\CurriculumThemeService',
    'App\Services\LearningOutcomeService' => 'App\Domain\Curriculum\Services\LearningOutcomeService',
    'App\Services\GenericSkillService' => 'App\Domain\Curriculum\Services\GenericSkillService',
    'App\Services\Contracts\SubjectServiceInterface' => 'App\Domain\Curriculum\Services\Contracts\SubjectServiceInterface',
    'App\Services\Contracts\ClassSubjectServiceInterface' => 'App\Domain\Curriculum\Services\Contracts\ClassSubjectServiceInterface',
    'App\Services\Contracts\SubjectTeacherServiceInterface' => 'App\Domain\Curriculum\Services\Contracts\SubjectTeacherServiceInterface',
    'App\Services\Contracts\CurriculumThemeServiceInterface' => 'App\Domain\Curriculum\Services\Contracts\CurriculumThemeServiceInterface',
    'App\Services\Contracts\LearningOutcomeServiceInterface' => 'App\Domain\Curriculum\Services\Contracts\LearningOutcomeServiceInterface',
    'App\Services\Contracts\GenericSkillServiceInterface' => 'App\Domain\Curriculum\Services\Contracts\GenericSkillServiceInterface',
    'App\Repositories\Eloquent\SubjectRepository' => 'App\Domain\Curriculum\Repositories\Eloquent\SubjectRepository',
    'App\Repositories\Eloquent\ClassSubjectRepository' => 'App\Domain\Curriculum\Repositories\Eloquent\ClassSubjectRepository',
    'App\Repositories\Eloquent\SubjectTeacherRepository' => 'App\Domain\Curriculum\Repositories\Eloquent\SubjectTeacherRepository',
    'App\Repositories\Eloquent\CurriculumThemeRepository' => 'App\Domain\Curriculum\Repositories\Eloquent\CurriculumThemeRepository',
    'App\Repositories\Eloquent\LearningOutcomeRepository' => 'App\Domain\Curriculum\Repositories\Eloquent\LearningOutcomeRepository',
    'App\Repositories\Eloquent\GenericSkillRepository' => 'App\Domain\Curriculum\Repositories\Eloquent\GenericSkillRepository',
    'App\Repositories\Contracts\SubjectRepositoryInterface' => 'App\Domain\Curriculum\Repositories\Contracts\SubjectRepositoryInterface',
    'App\Repositories\Contracts\ClassSubjectRepositoryInterface' => 'App\Domain\Curriculum\Repositories\Contracts\ClassSubjectRepositoryInterface',
    'App\Repositories\Contracts\SubjectTeacherRepositoryInterface' => 'App\Domain\Curriculum\Repositories\Contracts\SubjectTeacherRepositoryInterface',
    'App\Repositories\Contracts\CurriculumThemeRepositoryInterface' => 'App\Domain\Curriculum\Repositories\Contracts\CurriculumThemeRepositoryInterface',
    'App\Repositories\Contracts\LearningOutcomeRepositoryInterface' => 'App\Domain\Curriculum\Repositories\Contracts\LearningOutcomeRepositoryInterface',
    'App\Repositories\Contracts\GenericSkillRepositoryInterface' => 'App\Domain\Curriculum\Repositories\Contracts\GenericSkillRepositoryInterface',
    'App\Http\Requests\SubjectRequest' => 'App\Domain\Curriculum\Requests\SubjectRequest',
    'App\Http\Requests\ClassSubjectRequest' => 'App\Domain\Curriculum\Requests\ClassSubjectRequest',
    'App\Http\Requests\SubjectTeacherRequest' => 'App\Domain\Curriculum\Requests\SubjectTeacherRequest',
    'App\Http\Requests\CurriculumThemeRequest' => 'App\Domain\Curriculum\Requests\CurriculumThemeRequest',
    'App\Http\Requests\LearningOutcomeRequest' => 'App\Domain\Curriculum\Requests\LearningOutcomeRequest',
    'App\Http\Requests\GenericSkillRequest' => 'App\Domain\Curriculum\Requests\GenericSkillRequest',
    'App\Http\Resources\SubjectResource' => 'App\Domain\Curriculum\Resources\SubjectResource',
    'App\Http\Resources\SubjectCollection' => 'App\Domain\Curriculum\Resources\SubjectCollection',
    'App\Http\Resources\ClassSubjectResource' => 'App\Domain\Curriculum\Resources\ClassSubjectResource',
    'App\Http\Resources\ClassSubjectCollection' => 'App\Domain\Curriculum\Resources\ClassSubjectCollection',
    'App\Http\Resources\SubjectTeacherResource' => 'App\Domain\Curriculum\Resources\SubjectTeacherResource',
    'App\Http\Resources\SubjectTeacherCollection' => 'App\Domain\Curriculum\Resources\SubjectTeacherCollection',
    'App\Http\Resources\CurriculumThemeResource' => 'App\Domain\Curriculum\Resources\CurriculumThemeResource',
    'App\Http\Resources\CurriculumThemeCollection' => 'App\Domain\Curriculum\Resources\CurriculumThemeCollection',
    'App\Http\Resources\LearningOutcomeResource' => 'App\Domain\Curriculum\Resources\LearningOutcomeResource',
    'App\Http\Resources\LearningOutcomeCollection' => 'App\Domain\Curriculum\Resources\LearningOutcomeCollection',
    'App\Http\Resources\GenericSkillResource' => 'App\Domain\Curriculum\Resources\GenericSkillResource',
    'App\Http\Resources\GenericSkillCollection' => 'App\Domain\Curriculum\Resources\GenericSkillCollection',
    'App\Providers\SubjectServiceProvider' => 'App\Domain\Curriculum\Providers\SubjectServiceProvider',
    'App\Providers\ClassSubjectServiceProvider' => 'App\Domain\Curriculum\Providers\ClassSubjectServiceProvider',
    'App\Providers\SubjectTeacherServiceProvider' => 'App\Domain\Curriculum\Providers\SubjectTeacherServiceProvider',
    'App\Providers\CurriculumThemeServiceProvider' => 'App\Domain\Curriculum\Providers\CurriculumThemeServiceProvider',
    'App\Providers\LearningOutcomeServiceProvider' => 'App\Domain\Curriculum\Providers\LearningOutcomeServiceProvider',
    'App\Providers\GenericSkillServiceProvider' => 'App\Domain\Curriculum\Providers\GenericSkillServiceProvider',

    // Assessment
    'App\Models\AssessmentType' => 'App\Domain\Assessment\Models\AssessmentType',
    'App\Models\GradingScale' => 'App\Domain\Assessment\Models\GradingScale',
    'App\Models\SkillRatingScale' => 'App\Domain\Assessment\Models\SkillRatingScale',
    'App\Models\AssessmentRecord' => 'App\Domain\Assessment\Models\AssessmentRecord',
    'App\Models\GenericSkillRating' => 'App\Domain\Assessment\Models\GenericSkillRating',
    'App\Models\SubjectTermResult' => 'App\Domain\Assessment\Models\SubjectTermResult',
    'App\Http\Controllers\Api\AssessmentTypeController' => 'App\Domain\Assessment\Controllers\AssessmentTypeController',
    'App\Http\Controllers\Api\GradingScaleController' => 'App\Domain\Assessment\Controllers\GradingScaleController',
    'App\Http\Controllers\Api\SkillRatingScaleController' => 'App\Domain\Assessment\Controllers\SkillRatingScaleController',
    'App\Http\Controllers\Api\AssessmentRecordController' => 'App\Domain\Assessment\Controllers\AssessmentRecordController',
    'App\Http\Controllers\Api\GenericSkillRatingController' => 'App\Domain\Assessment\Controllers\GenericSkillRatingController',
    'App\Http\Controllers\Api\SubjectTermResultController' => 'App\Domain\Assessment\Controllers\SubjectTermResultController',
    'App\Services\AssessmentTypeService' => 'App\Domain\Assessment\Services\AssessmentTypeService',
    'App\Services\GradingScaleService' => 'App\Domain\Assessment\Services\GradingScaleService',
    'App\Services\SkillRatingScaleService' => 'App\Domain\Assessment\Services\SkillRatingScaleService',
    'App\Services\AssessmentRecordService' => 'App\Domain\Assessment\Services\AssessmentRecordService',
    'App\Services\GenericSkillRatingService' => 'App\Domain\Assessment\Services\GenericSkillRatingService',
    'App\Services\SubjectTermResultService' => 'App\Domain\Assessment\Services\SubjectTermResultService',
    'App\Services\Contracts\AssessmentTypeServiceInterface' => 'App\Domain\Assessment\Services\Contracts\AssessmentTypeServiceInterface',
    'App\Services\Contracts\GradingScaleServiceInterface' => 'App\Domain\Assessment\Services\Contracts\GradingScaleServiceInterface',
    'App\Services\Contracts\SkillRatingScaleServiceInterface' => 'App\Domain\Assessment\Services\Contracts\SkillRatingScaleServiceInterface',
    'App\Services\Contracts\AssessmentRecordServiceInterface' => 'App\Domain\Assessment\Services\Contracts\AssessmentRecordServiceInterface',
    'App\Services\Contracts\GenericSkillRatingServiceInterface' => 'App\Domain\Assessment\Services\Contracts\GenericSkillRatingServiceInterface',
    'App\Services\Contracts\SubjectTermResultServiceInterface' => 'App\Domain\Assessment\Services\Contracts\SubjectTermResultServiceInterface',
    'App\Repositories\Eloquent\AssessmentTypeRepository' => 'App\Domain\Assessment\Repositories\Eloquent\AssessmentTypeRepository',
    'App\Repositories\Eloquent\GradingScaleRepository' => 'App\Domain\Assessment\Repositories\Eloquent\GradingScaleRepository',
    'App\Repositories\Eloquent\SkillRatingScaleRepository' => 'App\Domain\Assessment\Repositories\Eloquent\SkillRatingScaleRepository',
    'App\Repositories\Eloquent\AssessmentRecordRepository' => 'App\Domain\Assessment\Repositories\Eloquent\AssessmentRecordRepository',
    'App\Repositories\Eloquent\GenericSkillRatingRepository' => 'App\Domain\Assessment\Repositories\Eloquent\GenericSkillRatingRepository',
    'App\Repositories\Eloquent\SubjectTermResultRepository' => 'App\Domain\Assessment\Repositories\Eloquent\SubjectTermResultRepository',
    'App\Repositories\Contracts\AssessmentTypeRepositoryInterface' => 'App\Domain\Assessment\Repositories\Contracts\AssessmentTypeRepositoryInterface',
    'App\Repositories\Contracts\GradingScaleRepositoryInterface' => 'App\Domain\Assessment\Repositories\Contracts\GradingScaleRepositoryInterface',
    'App\Repositories\Contracts\SkillRatingScaleRepositoryInterface' => 'App\Domain\Assessment\Repositories\Contracts\SkillRatingScaleRepositoryInterface',
    'App\Repositories\Contracts\AssessmentRecordRepositoryInterface' => 'App\Domain\Assessment\Repositories\Contracts\AssessmentRecordRepositoryInterface',
    'App\Repositories\Contracts\GenericSkillRatingRepositoryInterface' => 'App\Domain\Assessment\Repositories\Contracts\GenericSkillRatingRepositoryInterface',
    'App\Repositories\Contracts\SubjectTermResultRepositoryInterface' => 'App\Domain\Assessment\Repositories\Contracts\SubjectTermResultRepositoryInterface',
    'App\Http\Requests\AssessmentTypeRequest' => 'App\Domain\Assessment\Requests\AssessmentTypeRequest',
    'App\Http\Requests\GradingScaleRequest' => 'App\Domain\Assessment\Requests\GradingScaleRequest',
    'App\Http\Requests\SkillRatingScaleRequest' => 'App\Domain\Assessment\Requests\SkillRatingScaleRequest',
    'App\Http\Requests\AssessmentRecordRequest' => 'App\Domain\Assessment\Requests\AssessmentRecordRequest',
    'App\Http\Requests\GenericSkillRatingRequest' => 'App\Domain\Assessment\Requests\GenericSkillRatingRequest',
    'App\Http\Requests\SubjectTermResultRequest' => 'App\Domain\Assessment\Requests\SubjectTermResultRequest',
    'App\Http\Resources\AssessmentTypeResource' => 'App\Domain\Assessment\Resources\AssessmentTypeResource',
    'App\Http\Resources\AssessmentTypeCollection' => 'App\Domain\Assessment\Resources\AssessmentTypeCollection',
    'App\Http\Resources\GradingScaleResource' => 'App\Domain\Assessment\Resources\GradingScaleResource',
    'App\Http\Resources\GradingScaleCollection' => 'App\Domain\Assessment\Resources\GradingScaleCollection',
    'App\Http\Resources\SkillRatingScaleResource' => 'App\Domain\Assessment\Resources\SkillRatingScaleResource',
    'App\Http\Resources\SkillRatingScaleCollection' => 'App\Domain\Assessment\Resources\SkillRatingScaleCollection',
    'App\Http\Resources\AssessmentRecordResource' => 'App\Domain\Assessment\Resources\AssessmentRecordResource',
    'App\Http\Resources\AssessmentRecordCollection' => 'App\Domain\Assessment\Resources\AssessmentRecordCollection',
    'App\Http\Resources\GenericSkillRatingResource' => 'App\Domain\Assessment\Resources\GenericSkillRatingResource',
    'App\Http\Resources\GenericSkillRatingCollection' => 'App\Domain\Assessment\Resources\GenericSkillRatingCollection',
    'App\Http\Resources\SubjectTermResultResource' => 'App\Domain\Assessment\Resources\SubjectTermResultResource',
    'App\Http\Resources\SubjectTermResultCollection' => 'App\Domain\Assessment\Resources\SubjectTermResultCollection',
    'App\Providers\AssessmentTypeServiceProvider' => 'App\Domain\Assessment\Providers\AssessmentTypeServiceProvider',
    'App\Providers\GradingScaleServiceProvider' => 'App\Domain\Assessment\Providers\GradingScaleServiceProvider',
    'App\Providers\SkillRatingScaleServiceProvider' => 'App\Domain\Assessment\Providers\SkillRatingScaleServiceProvider',
    'App\Providers\AssessmentRecordServiceProvider' => 'App\Domain\Assessment\Providers\AssessmentRecordServiceProvider',
    'App\Providers\GenericSkillRatingServiceProvider' => 'App\Domain\Assessment\Providers\GenericSkillRatingServiceProvider',
    'App\Providers\SubjectTermResultServiceProvider' => 'App\Domain\Assessment\Providers\SubjectTermResultServiceProvider',

    // Reports
    'App\Models\ReportCard' => 'App\Domain\Reports\Models\ReportCard',
    'App\Http\Controllers\Api\ReportCardController' => 'App\Domain\Reports\Controllers\ReportCardController',
    'App\Services\ReportCardService' => 'App\Domain\Reports\Services\ReportCardService',
    'App\Services\Contracts\ReportCardServiceInterface' => 'App\Domain\Reports\Services\Contracts\ReportCardServiceInterface',
    'App\Repositories\Eloquent\ReportCardRepository' => 'App\Domain\Reports\Repositories\Eloquent\ReportCardRepository',
    'App\Repositories\Contracts\ReportCardRepositoryInterface' => 'App\Domain\Reports\Repositories\Contracts\ReportCardRepositoryInterface',
    'App\Http\Requests\ReportCardRequest' => 'App\Domain\Reports\Requests\ReportCardRequest',
    'App\Http\Resources\ReportCardResource' => 'App\Domain\Reports\Resources\ReportCardResource',
    'App\Http\Resources\ReportCardCollection' => 'App\Domain\Reports\Resources\ReportCardCollection',
    'App\Providers\ReportCardServiceProvider' => 'App\Domain\Reports\Providers\ReportCardServiceProvider',

    // Attendance
    'App\Models\Attendance' => 'App\Domain\Attendance\Models\Attendance',
    'App\Http\Controllers\Api\AttendanceController' => 'App\Domain\Attendance\Controllers\AttendanceController',
    'App\Services\AttendanceService' => 'App\Domain\Attendance\Services\AttendanceService',
    'App\Services\Contracts\AttendanceServiceInterface' => 'App\Domain\Attendance\Services\Contracts\AttendanceServiceInterface',
    'App\Repositories\Eloquent\AttendanceRepository' => 'App\Domain\Attendance\Repositories\Eloquent\AttendanceRepository',
    'App\Repositories\Contracts\AttendanceRepositoryInterface' => 'App\Domain\Attendance\Repositories\Contracts\AttendanceRepositoryInterface',
    'App\Http\Requests\AttendanceRequest' => 'App\Domain\Attendance\Requests\AttendanceRequest',
    'App\Http\Resources\AttendanceResource' => 'App\Domain\Attendance\Resources\AttendanceResource',
    'App\Http\Resources\AttendanceCollection' => 'App\Domain\Attendance\Resources\AttendanceCollection',
    'App\Providers\AttendanceServiceProvider' => 'App\Domain\Attendance\Providers\AttendanceServiceProvider',

    // Timetable
    'App\Models\Timetable' => 'App\Domain\Timetable\Models\Timetable',
    'App\Http\Controllers\Api\TimetableController' => 'App\Domain\Timetable\Controllers\TimetableController',
    'App\Services\TimetableService' => 'App\Domain\Timetable\Services\TimetableService',
    'App\Services\Contracts\TimetableServiceInterface' => 'App\Domain\Timetable\Services\Contracts\TimetableServiceInterface',
    'App\Repositories\Eloquent\TimetableRepository' => 'App\Domain\Timetable\Repositories\Eloquent\TimetableRepository',
    'App\Repositories\Contracts\TimetableRepositoryInterface' => 'App\Domain\Timetable\Repositories\Contracts\TimetableRepositoryInterface',
    'App\Http\Requests\TimetableRequest' => 'App\Domain\Timetable\Requests\TimetableRequest',
    'App\Http\Resources\TimetableResource' => 'App\Domain\Timetable\Resources\TimetableResource',
    'App\Http\Resources\TimetableCollection' => 'App\Domain\Timetable\Resources\TimetableCollection',
    'App\Providers\TimetableServiceProvider' => 'App\Domain\Timetable\Providers\TimetableServiceProvider',

    // Finance
    'App\Models\FeeStructure' => 'App\Domain\Finance\Models\FeeStructure',
    'App\Models\Invoice' => 'App\Domain\Finance\Models\Invoice',
    'App\Models\Payment' => 'App\Domain\Finance\Models\Payment',
    'App\Http\Controllers\Api\FeeStructureController' => 'App\Domain\Finance\Controllers\FeeStructureController',
    'App\Http\Controllers\Api\InvoiceController' => 'App\Domain\Finance\Controllers\InvoiceController',
    'App\Http\Controllers\Api\PaymentController' => 'App\Domain\Finance\Controllers\PaymentController',
    'App\Services\FeeStructureService' => 'App\Domain\Finance\Services\FeeStructureService',
    'App\Services\InvoiceService' => 'App\Domain\Finance\Services\InvoiceService',
    'App\Services\PaymentService' => 'App\Domain\Finance\Services\PaymentService',
    'App\Services\Contracts\FeeStructureServiceInterface' => 'App\Domain\Finance\Services\Contracts\FeeStructureServiceInterface',
    'App\Services\Contracts\InvoiceServiceInterface' => 'App\Domain\Finance\Services\Contracts\InvoiceServiceInterface',
    'App\Services\Contracts\PaymentServiceInterface' => 'App\Domain\Finance\Services\Contracts\PaymentServiceInterface',
    'App\Repositories\Eloquent\FeeStructureRepository' => 'App\Domain\Finance\Repositories\Eloquent\FeeStructureRepository',
    'App\Repositories\Eloquent\InvoiceRepository' => 'App\Domain\Finance\Repositories\Eloquent\InvoiceRepository',
    'App\Repositories\Eloquent\PaymentRepository' => 'App\Domain\Finance\Repositories\Eloquent\PaymentRepository',
    'App\Repositories\Contracts\FeeStructureRepositoryInterface' => 'App\Domain\Finance\Repositories\Contracts\FeeStructureRepositoryInterface',
    'App\Repositories\Contracts\InvoiceRepositoryInterface' => 'App\Domain\Finance\Repositories\Contracts\InvoiceRepositoryInterface',
    'App\Repositories\Contracts\PaymentRepositoryInterface' => 'App\Domain\Finance\Repositories\Contracts\PaymentRepositoryInterface',
    'App\Http\Requests\FeeStructureRequest' => 'App\Domain\Finance\Requests\FeeStructureRequest',
    'App\Http\Requests\InvoiceRequest' => 'App\Domain\Finance\Requests\InvoiceRequest',
    'App\Http\Requests\PaymentRequest' => 'App\Domain\Finance\Requests\PaymentRequest',
    'App\Http\Resources\FeeStructureResource' => 'App\Domain\Finance\Resources\FeeStructureResource',
    'App\Http\Resources\FeeStructureCollection' => 'App\Domain\Finance\Resources\FeeStructureCollection',
    'App\Http\Resources\InvoiceResource' => 'App\Domain\Finance\Resources\InvoiceResource',
    'App\Http\Resources\InvoiceCollection' => 'App\Domain\Finance\Resources\InvoiceCollection',
    'App\Http\Resources\PaymentResource' => 'App\Domain\Finance\Resources\PaymentResource',
    'App\Http\Resources\PaymentCollection' => 'App\Domain\Finance\Resources\PaymentCollection',
    'App\Providers\FeeStructureServiceProvider' => 'App\Domain\Finance\Providers\FeeStructureServiceProvider',
    'App\Providers\InvoiceServiceProvider' => 'App\Domain\Finance\Providers\InvoiceServiceProvider',
    'App\Providers\PaymentServiceProvider' => 'App\Domain\Finance\Providers\PaymentServiceProvider',

    // Discipline
    'App\Models\DisciplineRecord' => 'App\Domain\Discipline\Models\DisciplineRecord',
    'App\Http\Controllers\Api\DisciplineRecordController' => 'App\Domain\Discipline\Controllers\DisciplineRecordController',
    'App\Services\DisciplineRecordService' => 'App\Domain\Discipline\Services\DisciplineRecordService',
    'App\Services\Contracts\DisciplineRecordServiceInterface' => 'App\Domain\Discipline\Services\Contracts\DisciplineRecordServiceInterface',
    'App\Repositories\Eloquent\DisciplineRecordRepository' => 'App\Domain\Discipline\Repositories\Eloquent\DisciplineRecordRepository',
    'App\Repositories\Contracts\DisciplineRecordRepositoryInterface' => 'App\Domain\Discipline\Repositories\Contracts\DisciplineRecordRepositoryInterface',
    'App\Http\Requests\DisciplineRecordRequest' => 'App\Domain\Discipline\Requests\DisciplineRecordRequest',
    'App\Http\Resources\DisciplineRecordResource' => 'App\Domain\Discipline\Resources\DisciplineRecordResource',
    'App\Http\Resources\DisciplineRecordCollection' => 'App\Domain\Discipline\Resources\DisciplineRecordCollection',
    'App\Providers\DisciplineRecordServiceProvider' => 'App\Domain\Discipline\Providers\DisciplineRecordServiceProvider',

    // Library
    'App\Models\LibraryBook' => 'App\Domain\Library\Models\LibraryBook',
    'App\Models\BookLoan' => 'App\Domain\Library\Models\BookLoan',
    'App\Http\Controllers\Api\LibraryBookController' => 'App\Domain\Library\Controllers\LibraryBookController',
    'App\Http\Controllers\Api\BookLoanController' => 'App\Domain\Library\Controllers\BookLoanController',
    'App\Services\LibraryBookService' => 'App\Domain\Library\Services\LibraryBookService',
    'App\Services\BookLoanService' => 'App\Domain\Library\Services\BookLoanService',
    'App\Services\Contracts\LibraryBookServiceInterface' => 'App\Domain\Library\Services\Contracts\LibraryBookServiceInterface',
    'App\Services\Contracts\BookLoanServiceInterface' => 'App\Domain\Library\Services\Contracts\BookLoanServiceInterface',
    'App\Repositories\Eloquent\LibraryBookRepository' => 'App\Domain\Library\Repositories\Eloquent\LibraryBookRepository',
    'App\Repositories\Eloquent\BookLoanRepository' => 'App\Domain\Library\Repositories\Eloquent\BookLoanRepository',
    'App\Repositories\Contracts\LibraryBookRepositoryInterface' => 'App\Domain\Library\Repositories\Contracts\LibraryBookRepositoryInterface',
    'App\Repositories\Contracts\BookLoanRepositoryInterface' => 'App\Domain\Library\Repositories\Contracts\BookLoanRepositoryInterface',
    'App\Http\Requests\LibraryBookRequest' => 'App\Domain\Library\Requests\LibraryBookRequest',
    'App\Http\Requests\BookLoanRequest' => 'App\Domain\Library\Requests\BookLoanRequest',
    'App\Http\Resources\LibraryBookResource' => 'App\Domain\Library\Resources\LibraryBookResource',
    'App\Http\Resources\LibraryBookCollection' => 'App\Domain\Library\Resources\LibraryBookCollection',
    'App\Http\Resources\BookLoanResource' => 'App\Domain\Library\Resources\BookLoanResource',
    'App\Http\Resources\BookLoanCollection' => 'App\Domain\Library\Resources\BookLoanCollection',
    'App\Providers\LibraryBookServiceProvider' => 'App\Domain\Library\Providers\LibraryBookServiceProvider',
    'App\Providers\BookLoanServiceProvider' => 'App\Domain\Library\Providers\BookLoanServiceProvider',

    // Announcements
    'App\Models\Announcement' => 'App\Domain\Announcements\Models\Announcement',
    'App\Http\Controllers\Api\AnnouncementController' => 'App\Domain\Announcements\Controllers\AnnouncementController',
    'App\Services\AnnouncementService' => 'App\Domain\Announcements\Services\AnnouncementService',
    'App\Services\Contracts\AnnouncementServiceInterface' => 'App\Domain\Announcements\Services\Contracts\AnnouncementServiceInterface',
    'App\Repositories\Eloquent\AnnouncementRepository' => 'App\Domain\Announcements\Repositories\Eloquent\AnnouncementRepository',
    'App\Repositories\Contracts\AnnouncementRepositoryInterface' => 'App\Domain\Announcements\Repositories\Contracts\AnnouncementRepositoryInterface',
    'App\Http\Requests\AnnouncementRequest' => 'App\Domain\Announcements\Requests\AnnouncementRequest',
    'App\Http\Resources\AnnouncementResource' => 'App\Domain\Announcements\Resources\AnnouncementResource',
    'App\Http\Resources\AnnouncementCollection' => 'App\Domain\Announcements\Resources\AnnouncementCollection',
    'App\Providers\AnnouncementServiceProvider' => 'App\Domain\Announcements\Providers\AnnouncementServiceProvider',

    // Shared
    'App\Providers\RepositoryServiceProvider' => 'App\Domain\Shared\Providers\RepositoryServiceProvider',
];

echo "Updating namespace references across all PHP files...\n";

$dirs = ['app', 'config', 'database', 'routes', 'tests', 'bootstrap'];
$count = 0;

foreach ($dirs as $dir) {
    if (!is_dir($dir)) continue;
    $it = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($dir));
    foreach ($it as $file) {
        if (!$file->isFile() || $file->getExtension() !== 'php') continue;
        
        $path = $file->getPathname();
        $content = file_get_contents($path);
        if ($content === false) continue;
        
        $original = $content;
        
        foreach ($oldToNew as $old => $new) {
            $content = str_replace($old, $new, $content);
        }
        
        if ($content !== $original) {
            file_put_contents($path, $content);
            $count++;
        }
    }
}

echo "Updated {$count} files.\n";
echo "Run composer dump-autoload...\n";
passthru('composer dump-autoload 2>&1');
echo "\nDone. Now run: php artisan test\n";
