const V1 = '/v1';

export const ENDPOINTS = {
  AUTH: {
    LOGIN: `${V1}/auth/login`,
    REGISTER: `${V1}/auth/register`,
    LOGOUT: `${V1}/auth/logout`,
    ME: `${V1}/auth/me`,
    FORGOT_PASSWORD: `${V1}/auth/forgot-password`,
    RESET_PASSWORD: `${V1}/auth/reset-password`,
    VERIFY_EMAIL: `${V1}/auth/verify-email`,
    RESEND_VERIFICATION: `${V1}/auth/resend-verification`,
  },
  ROLES: `${V1}/roles`,
  USERS: `${V1}/users`,
  ACADEMIC_YEARS: `${V1}/academic-years`,
  TERMS: `${V1}/terms`,
  CLASS_LEVELS: `${V1}/class-levels`,
  STREAMS: `${V1}/streams`,
  STAFF: `${V1}/staff`,
  STUDENTS: `${V1}/students`,
  STUDENTS_IMPORT: `${V1}/students/import`,
  STUDENTS_IMPORT_TEMPLATE: `${V1}/students/import/template`,
  GUARDIANS: `${V1}/guardians`,
  ENROLLMENTS: `${V1}/enrollments`,
  SUBJECTS: `${V1}/subjects`,
  CLASS_SUBJECTS: `${V1}/class-subjects`,
  SUBJECT_TEACHERS: `${V1}/subject-teachers`,
  CURRICULUM_THEMES: `${V1}/curriculum-themes`,
  LEARNING_OUTCOMES: `${V1}/learning-outcomes`,
  GENERIC_SKILLS: `${V1}/generic-skills`,
  ASSESSMENT_TYPES: `${V1}/assessment-types`,
  GRADING_SCALE: `${V1}/grading-scale`,
  SKILL_RATING_SCALE: `${V1}/skill-rating-scale`,
  ASSESSMENT_RECORDS: `${V1}/assessment-records`,
  GENERIC_SKILL_RATINGS: `${V1}/generic-skill-ratings`,
  SUBJECT_TERM_RESULTS: `${V1}/subject-term-results`,
  REPORT_CARDS: `${V1}/report-cards`,
  ATTENDANCE: `${V1}/attendance`,
  TIMETABLE: `${V1}/timetable`,
  FEE_STRUCTURES: `${V1}/fee-structures`,
  INVOICES: `${V1}/invoices`,
  PAYMENTS: `${V1}/payments`,
  DISCIPLINE_RECORDS: `${V1}/discipline-records`,
  LIBRARY_BOOKS: `${V1}/library-books`,
  BOOK_LOANS: `${V1}/book-loans`,
  ANNOUNCEMENTS: `${V1}/announcements`,
} as const;
